/**
 * Small badge shown on any AI-generated content.
 * Clearly distinguishes AI interpretation from deterministic calculations.
 */
interface AIBadgeProps {
  className?: string
}

export default function AIBadge({ className = '' }: AIBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-2xs font-medium
        bg-purple-950/50 border border-purple-700/40 text-purple-300 select-none ${className}`}
      title="This content was generated by Claude AI and is interpretive, not calculated."
    >
      ✦ AI
    </span>
  )
}
